# Generated by Django 3.1.7 on 2021-05-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
