# Generated by Django 3.1.7 on 2021-05-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(default='', max_length=40),
        ),
    ]
