# Generated by Django 3.1.7 on 2021-04-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='youtube_id',
            new_name='yt_code',
        ),
    ]
